# Generated by Django 3.2.3 on 2021-05-20 12:37

from django.db import migrations, models
import eshop_product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=eshop_product.models.generate_name_file)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
