# Generated by Django 3.2.3 on 2021-05-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_category', '0003_auto_20210530_1924'),
        ('eshop_product', '0002_auto_20210527_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='eshop_category.Category'),
        ),
    ]
