# Generated by Django 3.2.3 on 2021-06-03 07:25

from django.db import migrations, models
import django.db.models.deletion
import eshop_product.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0003_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=eshop_product.models.generate_name_file_for_gallery, verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
    ]
