# Generated by Django 3.2.3 on 2021-06-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0004_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='title',
            field=models.CharField(default='unkown', max_length=150, verbose_name='عنوان'),
            preserve_default=False,
        ),
    ]
