# Generated by Django 3.2.3 on 2021-06-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0005_productgallery_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='عنوان'),
        ),
    ]
