# Generated by Django 3.2.3 on 2021-05-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'تگ', 'verbose_name_plural': 'تگ ها'},
        ),
    ]
