# Generated by Django 3.2.3 on 2021-05-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_tag', '0003_alter_tag_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(verbose_name='url'),
        ),
    ]
