# Generated by Django 3.2.3 on 2021-06-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='address',
            field=models.CharField(default='ایـران - آذربایجـان غربـی - خـوی', max_length=250, verbose_name='آدرس'),
            preserve_default=False,
        ),
    ]
