# Generated by Django 3.2.3 on 2021-06-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0003_settings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo.png', verbose_name='لوگو'),
        ),
    ]
