# Generated by Django 3.2.3 on 2021-07-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_card', '0002_auto_20210608_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trcking_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='کد رهگیری'),
        ),
    ]
