# Generated by Django 3.2.3 on 2021-08-29 15:48

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.models.generate_name_file, verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('is_publish', models.BooleanField(default=False, verbose_name='انتشار/پیشنویس')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'خبرها',
            },
        ),
    ]
